name: book_store
description: A new Flutter project.
title: 真言藏

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  aligned_dialog: 0.0.6
  archive: ^3.4.10
  audioplayers: ^5.2.1
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  connectivity_wrapper: ^1.0.5
  cupertino_icons: ^1.0.0
  dio: ^5.4.2+1
  dropdown_button2: 2.0.0
  equatable: 2.0.5
  file_saver: ^0.2.6
  floating_bottom_navigation_bar: 1.5.2
  flutter:
    sdk: flutter
  flutter_animate: 4.1.1+1
  flutter_cache_manager: ^3.3.1
  flutter_config: ^2.0.2
  flutter_launcher_icons: ^0.12.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  get: ^4.6.6
  go_router: 7.1.1
  google_fonts: ^6.1.0
  http: null
  intl: ^0.18.1
  json_path: 0.6.2
  mime_type: 1.0.0
  no_screenshot: ^0.0.1+6
  page_transition: 2.0.4
  path_provider: 2.1.2
  path_provider_android: 2.1.0
  path_provider_foundation: 2.3.0
  path_provider_platform_interface: 2.1.0
  pdfrx: ^1.0.52
  permission_handler: ^11.3.0
  provider: 6.0.4
  riverpod: ^2.4.9
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sqflite: 2.2.6
  syncfusion_flutter_pdfviewer: ^23.2.7
  syncfusion_flutter_sliders: ^23.2.7
  timeago: 3.2.2
  top_snackbar_flutter: ^3.1.0
  url_launcher: 6.2.4
  url_launcher_android: 6.2.0
  url_launcher_ios: 6.2.0
  url_launcher_platform_interface: 2.2.0
  uuid: ^4.1.0
  video_player: ^2.8.1
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0

flutter_icons:
  image_path: "assets/images/LOGO1.png"

  android: true
  ios: true
  # remove_alpha_ios: true
  flutter_test:
    sdk: flutter
  pdf_render: ^1.4.0
  # syncfusion_flutter_pdf: ^23.2.7

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/media/audio.png
    - assets/media/video.png
    - assets/images/book.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
